Repository AY2425S1-CS2103-F13-2/tp, pull requests merged in 2024-11, with the labels that each got.

#153 Update UML Diagram for UI
  docs/diagrams/UiClassDiagram.puml
Labels: priority.High

#155 Add highlight to focused elements
  src/main/java/seedu/eventtory/ui/EventDetailsPanel.java
  src/main/java/seedu/eventtory/ui/EventListPanel.java
  src/main/java/seedu/eventtory/ui/MainWindow.java
  src/main/java/seedu/eventtory/ui/VendorDetailsPanel.java
  src/main/java/seedu/eventtory/ui/VendorListPanel.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/EventListPanel.fxml
  src/main/resources/view/Extensions.css
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/VendorListPanel.fxml
Labels: priority.High

#156 Allow find command to search through all fields
  src/main/java/seedu/eventtory/logic/commands/FindCommand.java
  src/main/java/seedu/eventtory/logic/commands/FindEventCommand.java
  src/main/java/seedu/eventtory/logic/commands/FindVendorCommand.java
  src/main/java/seedu/eventtory/logic/commands/util/PredicatePreviewUtil.java
  src/main/java/seedu/eventtory/logic/parser/FindCommandParser.java
  src/main/java/seedu/eventtory/model/event/EventContainsKeywordsPredicate.java
  src/main/java/seedu/eventtory/model/event/EventNameContainsKeywordsPredicate.java
  src/main/java/seedu/eventtory/model/vendor/NameContainsKeywordsPredicate.java
  src/main/java/seedu/eventtory/model/vendor/VendorContainsKeywordsPredicate.java
  src/test/java/seedu/eventtory/logic/commands/CommandTestUtil.java
  src/test/java/seedu/eventtory/logic/commands/FindEventCommandTest.java
  src/test/java/seedu/eventtory/logic/commands/FindVendorCommandTest.java
  src/test/java/seedu/eventtory/logic/parser/EventToryParserTest.java
  src/test/java/seedu/eventtory/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/eventtory/model/ModelManagerTest.java
  src/test/java/seedu/eventtory/model/event/EventContainsKeywordsPredicateTest.java
  src/test/java/seedu/eventtory/model/event/EventNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/eventtory/model/vendor/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/eventtory/model/vendor/VendorContainsKeywordsPredicateTest.java
Labels: priority.High

#166 Extra Test Folder after Renaming from Address Book to EventTory
  src/test/data/JsonSerializableAddressBookTest/invalidEventAddressBook.json
Labels: type.Chore, priority.High

#159 Add trailing indexing scheme in view mode
  src/main/java/seedu/eventtory/logic/Logic.java
  src/main/java/seedu/eventtory/logic/LogicManager.java
  src/main/java/seedu/eventtory/logic/commands/AssignCommand.java
  src/main/java/seedu/eventtory/logic/commands/DeleteEventCommand.java
  src/main/java/seedu/eventtory/logic/commands/DeleteVendorCommand.java
  src/main/java/seedu/eventtory/logic/commands/EditEventCommand.java
  src/main/java/seedu/eventtory/logic/commands/EditVendorCommand.java
  src/main/java/seedu/eventtory/logic/commands/UnassignCommand.java
  src/main/java/seedu/eventtory/logic/commands/ViewEventCommand.java
  src/main/java/seedu/eventtory/logic/commands/ViewVendorCommand.java
  src/main/java/seedu/eventtory/logic/commands/util/IndexResolverUtil.java
  src/main/java/seedu/eventtory/model/Model.java
  src/main/java/seedu/eventtory/model/ModelManager.java
  src/main/java/seedu/eventtory/ui/EventDetailsPanel.java
  src/main/java/seedu/eventtory/ui/EventListPanel.java
  src/main/java/seedu/eventtory/ui/VendorDetailsPanel.java
  src/main/java/seedu/eventtory/ui/VendorListPanel.java
  src/test/java/seedu/eventtory/logic/LogicManagerTest.java
  src/test/java/seedu/eventtory/logic/commands/AssignCommandTest.java
  src/test/java/seedu/eventtory/logic/commands/CreateEventCommandTest.java
  src/test/java/seedu/eventtory/logic/commands/CreateVendorCommandTest.java
  src/test/java/seedu/eventtory/logic/commands/EditEventCommandTest.java
  src/test/java/seedu/eventtory/logic/commands/util/IndexResolverUtilTest.java
  src/test/java/seedu/eventtory/model/ModelManagerTest.java
  src/test/java/seedu/eventtory/model/commons/tag/TagTest.java
  src/test/java/seedu/eventtory/testutil/EditEventDescriptorBuilder.java
  src/test/java/seedu/eventtory/testutil/EventUtil.java
  src/test/java/seedu/eventtory/testutil/ModelStub.java
  src/test/java/seedu/eventtory/testutil/TypicalIndexes.java
  src/test/java/seedu/eventtory/testutil/VendorBuilder.java
Labels: priority.High

#151 Revamp unassign from view mode for nested eventvendor list
  src/main/java/seedu/eventtory/logic/commands/UnassignCommand.java
  src/main/java/seedu/eventtory/logic/commands/ViewEventCommand.java
  src/main/java/seedu/eventtory/logic/commands/ViewVendorCommand.java
  src/main/java/seedu/eventtory/logic/parser/AssignCommandParser.java
  src/main/java/seedu/eventtory/logic/parser/UnassignCommandParser.java
  src/main/java/seedu/eventtory/model/ModelManager.java
  src/main/java/seedu/eventtory/model/util/PredicateBuilder.java
  src/test/java/seedu/eventtory/logic/LogicManagerTest.java
  src/test/java/seedu/eventtory/logic/commands/UnassignCommandTest.java
  src/test/java/seedu/eventtory/logic/commands/util/IndexResolverUtilTest.java
  src/test/java/seedu/eventtory/logic/parser/EventToryParserTest.java
  src/test/java/seedu/eventtory/logic/parser/UnassignCommandParserTest.java
  src/test/java/seedu/eventtory/model/ModelManagerTest.java
  src/test/java/seedu/eventtory/model/util/PredicateBuilderTest.java
Labels: priority.High

#170 "Vendors List" and "Events List" should be "Vendor List" and Event List" respectively (no 's')
  src/main/java/seedu/eventtory/ui/MainWindow.java
  src/main/resources/view/EventListPanel.fxml
  src/main/resources/view/VendorListPanel.fxml
Labels: type.Bug, priority.Low, severity.Low, alpha-bug

#174 Persist UniqueId when updating Event or Vendor
  src/main/java/seedu/eventtory/logic/commands/EditEventCommand.java
  src/main/java/seedu/eventtory/logic/commands/EditVendorCommand.java
Labels: type.Bug, priority.High, alpha-bug

#178 Fix navigate to default when eventTory is cleared
  src/main/java/seedu/eventtory/model/ModelManager.java
Labels: type.Bug, priority.High, priority.Medium, alpha-bug

#177 Return to default view when selected object is deleted
  src/main/java/seedu/eventtory/model/ModelManager.java
  src/main/java/seedu/eventtory/model/event/Event.java
  src/main/java/seedu/eventtory/model/vendor/Vendor.java
  src/main/java/seedu/eventtory/ui/UiState.java
  src/test/java/seedu/eventtory/logic/commands/DeleteEventCommandTest.java
  src/test/java/seedu/eventtory/logic/commands/DeleteVendorCommandTest.java
  src/test/java/seedu/eventtory/model/event/EventTest.java
  src/test/java/seedu/eventtory/model/vendor/VendorTest.java
Labels: type.Bug, priority.High, alpha-bug

#169 Tags are Case Sensitive
  src/main/java/seedu/eventtory/model/commons/tag/Tag.java
  src/main/java/seedu/eventtory/storage/JsonAdaptedTag.java
  src/test/java/seedu/eventtory/model/commons/tag/TagTest.java
Labels: type.Bug, priority.Low, severity.VeryLow, alpha-bug

#179 Update Assign Command to have Behaviour Consistent with the Updated Unassign Command
  src/main/java/seedu/eventtory/logic/Messages.java
  src/main/java/seedu/eventtory/logic/commands/AssignCommand.java
  src/main/java/seedu/eventtory/logic/commands/UnassignCommand.java
  src/main/java/seedu/eventtory/logic/parser/AssignCommandParser.java
  src/test/java/seedu/eventtory/logic/commands/AssignCommandTest.java
  src/test/java/seedu/eventtory/logic/commands/UnassignCommandTest.java
  src/test/java/seedu/eventtory/logic/parser/AssignCommandParserTest.java
  src/test/java/seedu/eventtory/logic/parser/EventToryParserTest.java
Labels: type.Enhancement, priority.High, alpha-bug

#172 Make inputs more forgiving
  src/main/java/seedu/eventtory/model/commons/name/Name.java
  src/main/java/seedu/eventtory/model/commons/tag/Tag.java
  src/test/java/seedu/eventtory/logic/commands/CommandTestUtil.java
  src/test/java/seedu/eventtory/logic/parser/CreateEventCommandParserTest.java
  src/test/java/seedu/eventtory/logic/parser/ParserUtilTest.java
  src/test/java/seedu/eventtory/model/commons/name/NameTest.java
  src/test/java/seedu/eventtory/storage/JsonAdaptedEventTest.java
  src/test/java/seedu/eventtory/storage/JsonAdaptedVendorTest.java
Labels: priority.Medium, severity.Medium, alpha-bug

#182 Amend tag tests to reflect forgiving inputs
  src/test/java/seedu/eventtory/model/commons/tag/TagTest.java
Labels: type.Bug, priority.High

#184 Add relative index of viewed object
  src/main/java/seedu/eventtory/logic/Logic.java
  src/main/java/seedu/eventtory/logic/LogicManager.java
  src/main/java/seedu/eventtory/model/Model.java
  src/main/java/seedu/eventtory/model/ModelManager.java
  src/main/java/seedu/eventtory/ui/EventDetailsPanel.java
  src/main/java/seedu/eventtory/ui/VendorDetailsPanel.java
  src/test/java/seedu/eventtory/logic/LogicManagerTest.java
  src/test/java/seedu/eventtory/testutil/ModelStub.java
Labels: priority.Medium, alpha-bug

#206 Update UG for edit command
  docs/UserGuide.md
Labels: type.Chore

#188 Update User Guide for delete Command
  docs/UserGuide.md
Labels: type.Chore, priority.High

#199 Update DG for logic component
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ParserClasses.puml
Labels: priority.High

#200 Update user guide for find command
  docs/UserGuide.md
  docs/images/findAlexDavidResult.png
Labels: type.Chore

#192 Add view in UG
  docs/UserGuide.md
Labels: type.Chore, priority.High

#212 Tag cannot display long inputs
  src/main/java/seedu/eventtory/model/commons/tag/Tag.java
  src/test/java/seedu/eventtory/model/commons/tag/TagTest.java
Labels: priority.High, severity.Medium, alpha-bug

#202 Update developer guide for storage component
  docs/DeveloperGuide.md
Labels: type.Chore

#211 Update User Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/helpMessage.png
Labels: type.Chore, priority.High

#214 Update `Ui.png`
  docs/images/Ui.png
Labels: type.Chore, priority.Medium

#217 Update user guide some more
  docs/UserGuide.md
Labels: type.Chore

#219 Fix bugs regarding viewed object index
  src/main/java/seedu/eventtory/logic/Logic.java
  src/main/java/seedu/eventtory/logic/LogicManager.java
  src/main/java/seedu/eventtory/logic/commands/ViewEventCommand.java
  src/main/java/seedu/eventtory/logic/commands/ViewVendorCommand.java
  src/main/java/seedu/eventtory/model/Model.java
  src/main/java/seedu/eventtory/model/ModelManager.java
  src/main/java/seedu/eventtory/ui/EventDetailsPanel.java
  src/main/java/seedu/eventtory/ui/VendorDetailsPanel.java
  src/main/resources/view/EventDetailsPanel.fxml
  src/main/resources/view/VendorDetailsPanel.fxml
  src/test/java/seedu/eventtory/logic/LogicManagerTest.java
  src/test/java/seedu/eventtory/testutil/ModelStub.java
Labels: type.Bug, severity.High, alpha-bug

#215 Add use case for delete and view
  docs/DeveloperGuide.md
Labels: type.Chore, priority.High

#220 Update user stories
  docs/DeveloperGuide.md
Labels: type.Chore

#222 Update index.md
  docs/index.md
Labels: type.Enhancement

#223 Add edit use case
  docs/DeveloperGuide.md
Labels: type.Chore, priority.High

#213 Add implementation details of the assign and unassign command to DG
  docs/DeveloperGuide.md
  docs/diagrams/AssignSequenceDiagram.puml
Labels: type.Chore

#226 Add list use case
  docs/DeveloperGuide.md
Labels: type.Chore, priority.High

#232 Update manual testing steps
  docs/DeveloperGuide.md
Labels: type.Chore

#233 Add find command use case
  docs/DeveloperGuide.md
Labels: type.Chore

#235 Fix minor formatting issue in manual testing guide
  docs/DeveloperGuide.md
Labels: priority.High

#238 236 update create comand in dg
  docs/DeveloperGuide.md
Labels: type.Chore

#243 Fix main sequence diagram
  docs/diagrams/ArchitectureSequenceDiagram.puml
Labels: priority.High

#246 Remove proposed implementation from DG
  docs/DeveloperGuide.md
Labels: type.Chore

#251 Fix assign command in user guide quick start
  docs/UserGuide.md
Labels: type.Bug, priority.Medium, severity.Medium

#330 Add disclaimer to partial commands
  docs/UserGuide.md
Labels: type.Bug

#334 Fix index 0 showing up after nested find and view operation
  src/main/java/seedu/eventtory/logic/commands/ViewEventCommand.java
  src/main/java/seedu/eventtory/logic/commands/ViewVendorCommand.java
Labels: type.Bug

#333 Better documentation for date formats
  docs/UserGuide.md
Labels: ped.documentationBug

#331 Add section for planned enhancements
  docs/DeveloperGuide.md
Labels: type.Bug

#340 Clarify trailing index behaviour and commands interactions
  docs/UserGuide.md
  docs/images/listIndexes.png
Labels: ped.documentationBug
