Repository AY2425S1-CS2103-F13-2/tp, pull requests merged in 2024-10, with the labels that each got.

#17 Add photo for kevin-pek
  docs/images/kevin-pek.png
Labels: type.Chore, priority.High

#14 Add photo of Jabez
  docs/images/jasperabez.png
Labels: type.Chore, priority.High

#8 Add Bo Chang's Photo
  docs/images/c5hives.png
Labels: type.Chore, priority.High

#23 Add hanscau image
  docs/images/hanscau.png
Labels: type.Chore, priority.High

#21 Update AboutUs page for hanscau
  docs/AboutUs.md
  docs/team/hanscau.md
Labels: type.Chore, priority.High

#24 Update AboutUs page for C5hives
  docs/AboutUs.md
  docs/team/c5hives.md
Labels: type.Chore, priority.High

#22 Update Jabez AboutUs details
  docs/AboutUs.md
  docs/team/jasperabez.md
Labels: type.Chore, priority.High

#31 Add AboutUs page for kahsuann
  docs/AboutUs.md
  docs/team/kahsuann.md
Labels: type.Chore, priority.High

#33 Update EventTory ui mockup
  docs/images/Ui.png
Labels: type.Chore, priority.Medium

#38 Add Acknowledgement for Original Source of Code in README (A3)
  README.md
Labels: type.Chore, priority.Medium

#47 Update Target User Profile & Value Proposition for Developer Guide (DG)
  docs/DeveloperGuide.md
Labels: type.Chore, priority.High

#48 Update NFR
  docs/DeveloperGuide.md
Labels: type.Chore, priority.High

#45 Add create event use case (DG)
  docs/DeveloperGuide.md
Labels: type.Chore, priority.High

#60 Update Glossary for Developer Guide (DG)
  docs/DeveloperGuide.md
Labels: type.Chore, priority.High

#58 Create event model stub
  src/main/java/seedu/address/model/event/Date.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/Name.java
  src/test/java/seedu/address/model/event/DateTest.java
  src/test/java/seedu/address/model/event/EventTest.java
  src/test/java/seedu/address/model/event/NameTest.java
Labels: type.Enhancement, priority.High

#63 Vendor parser support
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/CreateVendorCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/CreateVendorCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/VendorUtil.java
Labels: type.Enhancement, priority.High

#70 Add parser support for adding new events
  src/main/java/seedu/address/logic/commands/CreateEventCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/CreateEventCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/CreateEventCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CreateEventCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: type.Enhancement, priority.High

#82 Reworked current delete command for vendor delete
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteVendorCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteVendorCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: type.Enhancement, priority.High

#81 Implement UniqueEventList for parent model
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/UniqueEventList.java
  src/main/java/seedu/address/model/event/exceptions/DuplicateEventException.java
  src/main/java/seedu/address/model/event/exceptions/EventNotFoundException.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/event/EventTest.java
  src/test/java/seedu/address/model/event/UniqueEventListTest.java
Labels: type.Enhancement, priority.High

#87 Add Support for Deleting Event
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteEventCommand.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/EventNameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteEventCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/model/event/EventNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/EventBuilder.java
  src/test/java/seedu/address/testutil/TypicalEvents.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: priority.High

#89 Administrative chore
  .gitignore
  src/main/resources/view/MainWindow.fxml
Labels: type.Chore, priority.Low

#90 Refactor CreateEventCommand and CreateVendorCommand to stem from the same Parent Class
  src/main/java/seedu/address/logic/commands/CreateCommand.java
  src/main/java/seedu/address/logic/commands/CreateEventCommand.java
  src/main/java/seedu/address/logic/commands/CreateVendorCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CreateCommandParser.java
  src/main/java/seedu/address/logic/parser/CreateEventCommandParser.java
  src/main/java/seedu/address/logic/parser/CreateVendorCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CreateVendorCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CreateCommandParserTest.java
  src/test/java/seedu/address/logic/parser/CreateEventCommandParserTest.java
  src/test/java/seedu/address/logic/parser/CreateVendorCommandParserTest.java
  src/test/java/seedu/address/testutil/EventUtil.java
  src/test/java/seedu/address/testutil/VendorUtil.java
Labels: type.Chore, priority.High

#92 Allow events in memory to be persistent
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonSerializableAddressBookTest/duplicateEventAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateVendorAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidEventAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidVendorAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalEventsAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalVendorsAddressBook.json
  src/test/java/seedu/address/storage/JsonAdaptedEventTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
Labels: type.Enhancement, priority.High

#93 Implement Actual Logic for CreateEventCommand
  src/main/java/seedu/address/logic/commands/CreateEventCommand.java
  src/test/java/seedu/address/logic/commands/CreateEventCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/CreateEventCommandTest.java
  src/test/java/seedu/address/logic/commands/CreateVendorCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/CreateVendorCommandTest.java
Labels: type.Enhancement, priority.High

#83 Update model to include tags and add assign command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/AssignCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AssignCommandTest.java
  src/test/java/seedu/address/logic/commands/CreateEventCommandTest.java
  src/test/java/seedu/address/logic/commands/CreateVendorCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewVendorCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/AssignCommandParserTest.java
Labels: priority.High

#102 Set up single pane UI for vendor and event lists
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/ui/EventCard.java
  src/main/java/seedu/address/ui/EventListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/EventListCard.fxml
  src/main/resources/view/EventListPanel.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: type.Story, priority.High

#105 Add get associated vendors and events
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/CreateEventCommandTest.java
  src/test/java/seedu/address/logic/commands/CreateVendorCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.Story, priority.High

#99 Parser implementation for unassign
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/UnassignCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/UnassignCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AssignCommandTest.java
  src/test/java/seedu/address/logic/commands/CreateEventCommandTest.java
  src/test/java/seedu/address/logic/commands/CreateVendorCommandTest.java
  src/test/java/seedu/address/logic/commands/UnassignCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/UnassignCommandParserTest.java
Labels: priority.High

#107 Update delete command to display failure message for associated event/vendor
  src/main/java/seedu/address/logic/commands/DeleteEventCommand.java
  src/main/java/seedu/address/logic/commands/DeleteVendorCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/commons/exceptions/AssociationDeleteException.java
  src/test/java/seedu/address/logic/commands/DeleteEventCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteVendorCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/testutil/TypicalVendorsEventsCombined.java
Labels: priority.High

#109 Update app name for release
  build.gradle
  src/main/resources/view/MainWindow.fxml
Labels: priority.High, priority.Medium

#111 Bump version for v1.3 release
  src/main/java/seedu/address/MainApp.java
Labels: priority.High

#119 Revamp view behaviour
  src/main/java/seedu/address/ui/EventListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/VendorDetailsPanel.java
  src/main/java/seedu/address/ui/VendorListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/VendorDetailsPanel.fxml
Labels: type.Enhancement, priority.High

#127 Show tags given to vendor and events
  src/main/java/seedu/address/ui/EventDetailsPanel.java
  src/main/java/seedu/address/ui/VendorDetailsPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/EventDetailsPanel.fxml
  src/main/resources/view/VendorDetailsPanel.fxml
Labels: type.Enhancement, priority.Medium

#129 Consider model reuse between event and vendor
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/CreateEventCommandParser.java
  src/main/java/seedu/address/logic/parser/CreateVendorCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/commons/name/Name.java
  src/main/java/seedu/address/model/commons/tag/Tag.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/Name.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/model/vendor/Vendor.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/storage/JsonAdaptedVendor.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CreateCommandParserTest.java
  src/test/java/seedu/address/logic/parser/CreateEventCommandParserTest.java
  src/test/java/seedu/address/logic/parser/CreateVendorCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/commons/name/NameTest.java
  src/test/java/seedu/address/model/commons/tag/TagTest.java
  src/test/java/seedu/address/model/event/EventTest.java
  src/test/java/seedu/address/model/event/NameTest.java
  src/test/java/seedu/address/model/event/UniqueEventListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedEventTest.java
  src/test/java/seedu/address/storage/JsonAdaptedVendorTest.java
  src/test/java/seedu/address/testutil/EditVendorDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EventBuilder.java
  src/test/java/seedu/address/testutil/VendorBuilder.java
  src/test/java/seedu/address/testutil/VendorUtil.java
Labels: type.Chore, priority.Medium

#126 Standardize and update message usage descriptors
  src/main/java/seedu/address/logic/commands/CreateCommand.java
  src/main/java/seedu/address/logic/commands/CreateEventCommand.java
  src/main/java/seedu/address/logic/commands/CreateVendorCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
Labels: type.Chore

#121 Update Find Command from AB3
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindEventCommand.java
  src/main/java/seedu/address/logic/commands/FindVendorCommand.java
  src/main/java/seedu/address/logic/commands/util/PredicatePreviewUtil.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/event/EventNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/vendor/NameContainsKeywordsPredicate.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/commands/FindEventCommandTest.java
  src/test/java/seedu/address/logic/commands/FindVendorCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/event/EventNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/vendor/NameContainsKeywordsPredicateTest.java
Labels: priority.Medium

#128 Rework EditCommand to EditEventCommand and EditVendorCommand
  src/main/java/seedu/address/logic/commands/DeleteEventCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditEventCommand.java
  src/main/java/seedu/address/logic/commands/EditVendorCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/UniqueEventList.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/CreateEventCommandTest.java
  src/test/java/seedu/address/logic/commands/CreateVendorCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditEventCommandTest.java
  src/test/java/seedu/address/logic/commands/EditEventDescriptorTest.java
  src/test/java/seedu/address/logic/commands/EditVendorCommandTest.java
  src/test/java/seedu/address/logic/commands/EditVendorDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/event/UniqueEventListTest.java
  src/test/java/seedu/address/testutil/EditEventDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EditVendorDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EventUtil.java
  src/test/java/seedu/address/testutil/VendorUtil.java
Labels: priority.Medium

#133 Prep for v1.4 Release
  src/main/java/seedu/address/MainApp.java
Labels: type.Chore, priority.High

#134 Enable assertions
  build.gradle
Labels: type.Chore, priority.Medium

#136 Fix bugs related to tags
  src/main/java/seedu/address/ui/EventCard.java
  src/main/java/seedu/address/ui/EventDetailsPanel.java
  src/main/java/seedu/address/ui/VendorDetailsPanel.java
  src/main/resources/view/EventListCard.fxml
Labels: type.Bug, priority.Low

#106 Add support for storing list of associations
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/association/Association.java
  src/main/java/seedu/address/model/association/UniqueAssociationList.java
  src/main/java/seedu/address/model/association/exceptions/AssociationNotFoundException.java
  src/main/java/seedu/address/model/association/exceptions/DuplicateAssociationException.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/UniqueEventList.java
  src/main/java/seedu/address/model/id/UniqueId.java
  src/main/java/seedu/address/model/vendor/UniqueVendorList.java
  src/main/java/seedu/address/model/vendor/Vendor.java
  src/main/java/seedu/address/storage/JsonAdaptedAssociation.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/main/java/seedu/address/storage/JsonAdaptedVendor.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/EventDetailsPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/VendorDetailsPanel.java
  src/test/data/JsonSerializableAddressBookTest/duplicateEventAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateVendorAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidAssociationEventId.json
  src/test/data/JsonSerializableAddressBookTest/invalidAssociationVendorId.json
  src/test/data/JsonSerializableAddressBookTest/invalidEventAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidVendorAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalEventsAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalVendorsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/CreateEventCommandTest.java
  src/test/java/seedu/address/logic/commands/CreateVendorCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/association/AssociationTest.java
  src/test/java/seedu/address/model/association/UniqueAssociationListTest.java
  src/test/java/seedu/address/model/event/EventTest.java
  src/test/java/seedu/address/model/vendor/VendorTest.java
  src/test/java/seedu/address/storage/JsonAdaptedAssociationTest.java
  src/test/java/seedu/address/storage/JsonAdaptedEventTest.java
  src/test/java/seedu/address/storage/JsonAdaptedVendorTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/TypicalAssociations.java
  src/test/java/seedu/address/testutil/VendorBuilder.java
Labels: priority.High

#148 Update equality of list commands
  src/main/java/seedu/eventtory/logic/commands/ListCommand.java
  src/main/java/seedu/eventtory/logic/commands/ListEventCommand.java
  src/main/java/seedu/eventtory/logic/commands/ListVendorCommand.java
  src/test/java/seedu/eventtory/logic/commands/ListCommandTest.java
  src/test/java/seedu/eventtory/logic/commands/ListEventCommandTest.java
  src/test/java/seedu/eventtory/logic/commands/ListVendorCommandTest.java
Labels: type.Bug, severity.Low

#146 Make Date Inputs More Flexible
  src/main/java/seedu/eventtory/model/event/Date.java
  src/test/data/JsonSerializableAddressBookTest/invalidEventAddressBook.json
  src/test/data/JsonSerializableEventToryTest/invalidEventEventTory.json
  src/test/java/seedu/eventtory/logic/parser/CreateEventCommandParserTest.java
  src/test/java/seedu/eventtory/logic/parser/ParserUtilTest.java
  src/test/java/seedu/eventtory/model/event/DateTest.java
  src/test/java/seedu/eventtory/model/event/EventTest.java
  src/test/java/seedu/eventtory/storage/JsonAdaptedEventTest.java
Labels: type.Enhancement, priority.Medium

#147 Update UML Diagram for Storage Component
  docs/diagrams/StorageClassDiagram.puml
Labels: type.Chore, priority.High

#138 Update ModelClassDiagram with new fields and event model
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Chore, priority.Medium
